### ISSUE TITLE
[BUG/ISSUE] Conflict with Quark beta 1.20.1

### ISSUE THREAD

**Issue by PinkLasagna03** [CERBON-MODS/CERBONs-Better-Beacons-FORGE#6]
## Minecraft Version
Forge 1.20.1

## Describe the bug
Crash with using the beta of quark while loading

## To Reproduce
Simple modpack using Forge 47.2.20, installed Better Beacons and Quark public Beta from their discord.

## Expected behavior
Starts up normally

## Latest Log

[latest.log](https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/files/13953576/latest.log)

## Additional context
First posted this on the Github of Quark 
[This post](https://github.com/VazkiiMods/Quark/issues/4588)

**Comment by Vazkii** [comment]
Given that the feature in Better Beacons is 1:1 to the one in quark, I don't see the point for the mixin to even load at all when Quark is enabled.

Either way, I personally find it very in bad taste to just take an entire quark feature's code and implementation wholesale as a feature in a mod whose core is something else, even if the license allows for it.

**Comment by CerbonXD** [comment]
Hi @Vazkii, I don't really understand your disappointment. Yes, I used your code in my project. It's a fact. However, it's not a 1:1 copy. I would say it's more like 0.9~0.95:1 because I made slight changes to the code to make it more configurable for the end user. That's why I don't remove my implementation if Quark is installed.

> I also find it incredibly ironic that you choose to include a code of conduct in place of a readme when you also chose to both name the mod after yourself, and hide the credit for one of its features in a random root-level md file no one's going to read. I can't tell if this is due to negligence or a desire to be only slightly above water for plagiarism, but either way, I'm not a fan.

The whole purpose of an open-source project is to let people see and use your code as long as they follow the requirements of the license attached to the project. That's exactly what I did. I used the same license to avoid problems. Also, as far as I know, having a CREDITS.md file in the root of the project is one of the ways to give proper credits to the original author. It's even more noticeable for non-programmers. What does the Code of Conduct have to do with it?

> Even more so to put it as a feature in a mod whose core is something else

The purpose of the mod is to improve beacons, so how is it not related? I saw the suggestions for [beam redirection](https://www.reddit.com/r/minecraftsuggestions/comments/j8xp1u/crystals_from_geodes_should_redirect_beacon_lasers/) and [transparency](https://www.reddit.com/r/minecraftsuggestions/comments/jrxhat/tinted_glass_should_make_beacon_beams_invisible/) on Reddit and discovered you had already implemented it in your mod. So, I decided to use it instead of creating one from scratch.

Talking about the issue itself, I knew that as soon as you updated to 1.20.1, both mods wouldn't work together. I had a workaround prepared for when this day comes, without needing to ask you to change your code. It's the same approach used for the 1.18.2 and 1.19.2 versions of the mod.

Anyway, what would you like me to do? Do you want me to credit you more explicitly (for example, in the CurseForge description), remove the implementation, or add comments to the code referencing the Quark's project?

I don't want to have any problems, so please let me know what I should do.

**Comment by CerbonXD** [comment]
Done.

I will release the compatibility fix soon btw @PinkLasagna03. Thanks for sending the issue.

**Comment by CerbonXD** [comment]
Version 1.1.1 is now available on CurseForge. You shouldn't have crashes anymore. It's still recommended to disable the `Beacon Redirection Module` from `Quark` tho. If you have any other issue please let me know.
